services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    apply_environment.command.addgit:
        class: Sioweb\ApplyEnvironment\Command\AddGitCommand
    apply_environment.command.environment:
        class: Sioweb\ApplyEnvironment\Command\ApplyEnvironmentCommand
